version: '2.3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:16.3'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=secret'
    networks:
      - app-network

  app:
    container_name: application
    build: .
    networks:
      - app-network
    ports:
      - '8080:8080'
    depends_on:
      - postgres

networks:
  app-network: